char *quote[] = {"You do not find the \nhappy life. You make\nit", 
					"The most wasted of  \ndays is one without \nlaughter",
					"Stay close to       \nanything that makes \nyou glad you are    \nalive",
					"Make each day your  \nmasterpiece",
					"Happiness often     \nsneaks in through a \ndoor you did not    \nknow you left open",
					"Happiness is not by \nchance, but by      \nchoice",
					"Life changes very   \nquickly, in a very  \npositive way, if you\nlet it",
					"Keep your face to   \nthe sunshine and you\ncannot see a shadow",
					"Impossible is for   \nthe unwilling",
					"No pressure, no     \ndiamonds",
					"Believe you can and \nyou are halfway     \nthere",
					"Failure is the      \ncondiment that gives\nsuccess its flavor",
					"It is never too late\nto be what you might\nhave been",
					"When you have a     \ndream, you have got \nto grab it and never\nlet go",
					"You must be the     \nchange you wish to  \nsee in the world",
					"Stay foolish to stay\nsane",
					"Stay hungry. Stay  \nfoolish",
					"Whatever you are, be\na good one",
					"You must do the     \nthings you think you\ncannot do",
					"I am starting to    \nthink this world is \njust a place for us \nto learn that we    \nneed each other more\nthan we want to    \nadmit",
					"Wherever you go, go \nwith all your heart",
					"Be faithful to that \nwhich exists within \nyourself",
					"Dream big and dare  \nto fail",
					"My mission in life  \nis not merely to    \nsurvive, but to     \nthrive",
					"You are enough just \nas you are",
					"To be the best, you \nmust be able to     \nhandle the worst",
					"Every moment is a   \nfresh beginning",
					"No guts, no story", 
					"Keep going. Be all  \nin",
					"Leave no stone      \nunturned",
					"Life is like riding \na bicycle. To keep  \nyour balance, you   \nmust keep moving",
					"Nothing is          \nimpossible. The word\nitself says I am    \npossible",
					"If it matters to    \nyou, you will find a\nway",
					"Tough times never   \nlast, but tough     \npeople do",
					"Turn your wounds    \ninto wisdom",
					"It is not where you \ncame from. It is    \nwhere you are going \nthat counts",
					"If you are going    \nthrough hell, keep  \ngoing",
					"Do not wait, the    \ntime will never be  \njust right",
					"The journey of a    \nthousand miles      \nbegins with a single\nstep",
					"If I cannot do great\nthings, I can do    \nsmall things in a   \ngreat way",
					"No matter what you  \nare going through,  \nthere is a light at \nthe end of the      \ntunnel",
					"Life is fragile. We \nare not guaranteed a\ntomorrow so give it \neverything you have \ngot",
					"The bad news is time\nflies. The good news\nis you are the pilot",
					"Some people look for\n a beautiful place. \nOthers make a place \nbeautiful",
					"Never let your sense\n of morals prevent  \nyou from doing what \nis right",
					"We have a           \nresponsibility to   \nhelp those around us\nand help others in  \nneed",
					"No one has ever     \nbecome poor by      \ngiving",
					"Try Again. Fail     \nagain. Fail better",
					"No one is useless in\nthis world who      \nlightens the burdens\nof others",
					"The only thing that \ncan grow is the     \nthing you give      \nenergy to",
					"Good things happen  \nto those who hustle",
					};
